dj_pd/csvs/urls.py
from django.urls import path
from .views import  upload_file_view
app_name = 'csvs'
urlpatterns = [
    path('', upload_file_view, name='upload-view'),]
    
    

dj_pd/dj_pd/urls.py
import imp
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('performance/', include('products.urls',namespace='products')),
    path('upload/',include('csvs.urls',namespace='csvs')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dj_pd/products/urls.py
from django.urls import path
from .views import chart_select_view,add_purchase_view
app_name = 'products'
urlpatterns = [
    path('', chart_select_view, name='main-products-view'),
    path('add/', add_purchase_view, name='add-purchase-view'),
]
    

dj_pd/csvs/models.py
from django.db import models

# Create your models here
class Csv(models.Model):
    file_name = models.FileField(upload_to='csvs/', max_length=100)
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)
    def _str_(self):
         return "File id: (0". format(self.id)

dj_pd/products/models.py
from django.db import models
from django.contrib.auth.models import User
from pytz import timezone
from django.utils import timezone

# Create your models here.
class Product(models. Model):
    name = models.CharField(max_length=220)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
         return str(self.name)

class Purchase(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity =models.PositiveIntegerField()
    total_price =models.PositiveIntegerField(blank=True)
    salesman = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
     self.total_price= self.price*self.quantity
     super().save(*args,**kwargs)

    def __str__(self):
     return "Solled {} - {}  items for {}".format(self.product.name, self.quantity, self.total_price)

dj_pd/csvs/forms.py
from django import forms
from .models import Csv
class CsvForm(forms.ModelForm):
    class Meta:
         model = Csv
         fields= ['file_name']

dj_pd/products/forms.py
from django import forms
from .models import Purchase,Product
class PurchaseForm(forms.ModelForm):
    products=forms.ModelChoiceField(queryset=Product.objects.all(),
    label='Product',widget=forms.Select(attrs={'class':'ui selection dropdown field-with'}))
    class Meta:
        model = Purchase
        fields = ['product', 'price', 'quantity'] 

dj_pd/csvs/views.py
from os import read
from django.shortcuts import render
from numpy import product
from .forms import CsvForm
from .models import Csv
import csv
from django.contrib.auth.models import User
from products.models import Product,Purchase
# Create your views here.

def upload_file_view( request):
     form = CsvForm( request.POST or None, request.FILES or None)
     if form.is_valid():
          form.save()
          form = CsvForm()
          obj=Csv.objects.get(activated=False)#process it 
          obj.activated=True#change it 
          obj.save()
          with open(obj.file_name.path,'r')as f:
               reader=csv.reader(f)
               for row in reader:
                    #print(row)
                    #row="".join(row)
                    #print(row)
                    #row=row.replace(",","")    
                    print(row)
                    #row=row.split()
                    print(type(row))
                   # user=User.objects.get(id=row[3])
                  #  Prod,_=Product.object.get_or_create(name=row[0])
                    
                   # print(user)
         
     context={
          'form': form,}
     return render(request, 'csvs/upload.html', context)    
    

dj_pd/products/views.py
from django.shortcuts import render
from .models import Product,Purchase
import pandas as pd
from .utils import get_simple_plot
from .forms import PurchaseForm
# Create your views here.
def chart_select_view(request):
     graph=None
     error_msg=None
     df=None#init
     price=None
     #qs=Product.objects.all()
     try:
         product_df = pd.DataFrame(Product.objects.all().values()) 
         purchase_df = pd.DataFrame(Purchase.objects.all().values())#.values_list()for indexs
         product_df['product_id']= product_df['id']
     except:
         product_df=None
         purchase_df=None
     if purchase_df:    
       if purchase_df.shape[0]>0 :
           df=pd.merge(purchase_df,product_df,on='product_id').drop(['id_y','date_y'],axis=1).rename({'id_x':'id','date_x':'date'},axis=1)#manipulating dataframe
           price=df['price']
           print(df['date'][0])#date of the first object
           print(type(df['date'][0]))#date of the first object
           if request.method == 'POST':
              
               chart_type=request.POST.get('sales')
               date_from=request.POST.get('date_from')
               date_to=request.POST.get('date_to')
               #print(chart_type)
               df ['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
               df2 = df.groupby( 'date', as_index=False)['total_price'].agg('sum')
              # print(df2['date'])
               if chart_type !="":
                     if date_from !="" and date_to != "":
                         df = df[(df['date']>date_from) & (df['date']< date_to)]
                         #print(type(df))
                         df2 = df.groupby('date', as_index=False)['total_price'].agg('sum')
                            # function to get a graph
                     graph=get_simple_plot(chart_type,x=df2['date'],y=df2['total_price'],data=df)
               else:
                    error_msg = 'Please select a chart type to continue'
     else:
                error_msg='No records in the database'
               

               
     context={
          
         #'products':product_df.to_html(),
         #'purchase':purchase_df.to_html(),
      #   'df':df.to_html(),
         'price':price,
         'graph':graph,
         'error_msg':error_msg, 
         #'df':df,
    }
     return render(request, 'products/main.html',context)



def add_purchase_view(request):
   
   form=PurchaseForm(request.POST or None)
   added_msg=None
   if form.is_valid():
      obj=form.save(commit=False)
      obj.salesman=request.user
      obj.save()
      form=PurchaseForm()
      added_msg="the purchase has been added"
   context={'form':form,'added_msg':added_msg}
   return render(request,'products/add.html',context)

dj_pd/csvs/templates/csvs/upload.html
{%extends 'base.html'%}
{% block title%}upload{%endblock title%}
{%block content %}
    <h1>upload</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="ui form">
         {%csrf_token%}
         {{ form }}
         <button type="submit" class="ui positive button">Add data</button>
    </form>
{%endblock content%}

dj_pd/products/templates/products/add.html
{% extends 'base.html'%}
{% block title %}
Add purchase
{% endblock title%}
{% block content %} 
{% if added_msg %}
<div class="ui success message">
    <i class="close icon"></i>
    <div class="header">
      {{added_msg}}
    </div>
    
  </div>
{% endif %}
 
<form action="" method="POST" class="ui form">
    {% csrf_token %}
    {{form }}
    <button type='submit' class='ui positive button mtop'>Add sales data</button>

</form>
{% endblock content %} 

dj_pd/products/templates/products/main.html
{% extends 'base.html'%}
{% block title %}
performance
{% endblock title%}

{% block content %}  
<div class="ui nodal my modal">
 <div class="header">Price</div>
 <div class="ui container">
        <ul><li>
            
           
                <li><strong>Count: </strong >{{ price.count }}</li>
                <li><strong> Mean: </strong></strong>{{price.mean}}</li>
                <li><strong>Medain: </strong> {{ price.median }}</li>
                <li><strong> Min: </strong> {{ price.min }}</li>
                <li><strong>Max: </strong>{{ price.max }}</li>
                <li><strong>Std dev: </strong> {{ price.std|floatformat }}</li>
         
        
        </ul>          
 </div>
</div>




    <hr>
    <div>
    <div class="block-center">
        {% if error_msg %}

        <div class="ui negative message">
            <i class="close icon"></i>
            <div class="header">
                {{error_msg}}  
            </div>
            </div>
        
        {%endif%}

        {% if request.POST %}
        {% if graph %}
                     <img src="data:image/png;base64, {{graph|safe}}">
        {% endif %}
        {% endif %}
        </div>
        <form action="" method="POST" class="ui form">
            {% csrf_token %}
            <div class="field">
                <label>Choose a chart type </label>
                <div class="ui selection dropdown">
                    <input type="hidden"name="sales">
                    <i class="dropdown icon"></i>
                    <div class="default text">------</div>
                    <div class="menu">
                        <div class="item" value="bar">Bar plot</div>
                        <div class="item" value="line">line plot </div>
                        <div class="item" value="count">Count plot</div>
                    </div>
                </div>
            </div>
            <div class="field">
                <label>Date from :</label>
                <div class="two fields">
                <div class="field">
                    <label>Date from :</label>
                   <input type="date" name="date_from" >
                </div>
                <div class="field">
                    <label>Date from :</label>
                   <input type="date" name="date_to">
                </div>
            </div>
          </div>
          <div class="block-center">
          <button class="ui primary button" type="submit">select</button>
        </div>
        </form>
        <div class="block-center">
        <button class="ui secondary button" id="modal-btn">
        See summary
        </button>
        <br>
        <a href={% url 'products:add-purchase-view' %} ><button class='ui positive button'>Add records</button></a>
    </div>

    </div>
{% endblock content %}

dj_pd/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel='stylesheet' type='text/css' href={% static '/style.css' %} >
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title> DJ PD Proj{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html'%}  
      <div class ='ui container'>
    {% block content %}
    {% endblock content %}
      </div>
      <script type="text/javascript" src={% static '/main.js' %} ></script>

  </body>
</html> 

dj_pd/templates/navbar.html
{% url 'products:main-products-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
<div class="ui secondary pointing menu">
    <a class="active item">
      Home
    </a>
    <a href={{path_to_performance}} class=" {%if request.path == path_to_performance%}active{%endif %} item">
      Performance
    </a>
    <a href={{path_to_adding_records}} class=" {%if request.path == path_to_adding_records%}active{%endif %} item">
      Add records
    </a>
    <a href={{path_to_upload}} class=" {%if request.path == path_to_upload%}active{%endif %} item">
      Upload
    </a>
    <div class="right menu">
      <a class="ui item">
        Logout
      </a>
    </div>
  </div>
 